name: Apply Formatting

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install black isort

      - name: Apply Black formatting
        run: black --line-length 120 .

      - name: Apply isort import formatting
        run: isort .

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Apply Black formatting" || echo "Commit failed or nothing to do, continuing workflow"

      - name: Push changes
        if: ${{ success() }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main