name: Apply Formatting and Update Changelog

on:
  push:
    branches:
      - main

jobs:
  format_and_update_changelog:
    runs-on: ubuntu-latest
    env:
      CHANGELOG_FILE: CHANGELOG.md

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install black isort pipreqs

      - name: Formatting
        run: |
          black --line-length 120 .
          isort .
          pipreqs --force --clean requirements.txt 2>/dev/null
          pipreqs --force . 2>/dev/null

      - name: Diagnose Commits
        run: |
          git log -20 --pretty=format:"%h %s"
      #      - name: Generate Changelog
      #        run: |
      #          categories=("Features" "Improvements" "Bug Fixes" "Others")
      #          patterns=("\[feature\(s\)\?\]" "\[improvement\(s\)\?\]" "\[bugfix\(es\)\?\]" "\[other\(s\)\?\]")
      #          echo -n "" > ${{ env.CHANGELOG_FILE }}
      #          for i in "${!categories[@]}"; do
      #            entries=$(git log -10 --pretty=format:"%h %s" | grep -i "${patterns[$i]}" | sed -E "s/${patterns[$i]} //" | awk '{print "- ["$1"] "substr($0, index($0,$2))}')
      #            if [ -n "$entries" ]; then
      #              echo -e "> ${categories[$i]}:\n$entries\n" >> ${{ env.CHANGELOG_FILE }}
      #            fi
      #          done

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Apply Black formatting and Update Changelog" || echo "No changes to commit, continuing workflow"

      - name: Push changes
        if: ${{ success() }}
        run: git push
